name: agawin_unievent_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter 
  font_awesome_flutter: ^10.8.0
  material_symbols_icons: ^4.2815.0
  flutter_launcher_icons: ^0.14.3
  supabase_flutter: ^2.8.4
  equatable: ^2.0.7
  intl: ^0.20.2
  flutter_bloc: ^9.1.0
  file_picker: ^10.1.2
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/images/
  uses-material-design: true
  
